var annotated_dup =
[
    [ "std", null, [
      [ "graphic", null, [
        [ "image", "dc/d67/classstd_1_1graphic_1_1image.html", "dc/d67/classstd_1_1graphic_1_1image" ]
      ] ],
      [ "internal", null, [
        [ "_mod< Tp, m, a, c, true, s >", "d7/da4/structstd_1_1internal_1_1__mod_3_01_tp_00_01m_00_01a_00_01c_00_01true_00_01s_01_4.html", null ],
        [ "alignof_helper", "d7/d18/structstd_1_1internal_1_1alignof__helper.html", "d7/d18/structstd_1_1internal_1_1alignof__helper" ],
        [ "compare_func", "dc/d6a/structstd_1_1internal_1_1compare__func.html", "dc/d6a/structstd_1_1internal_1_1compare__func" ],
        [ "list_base_node", "dc/db6/structstd_1_1internal_1_1list__base__node.html", "dc/db6/structstd_1_1internal_1_1list__base__node" ],
        [ "rb_tree_base", "d2/d6c/structstd_1_1internal_1_1rb__tree__base.html", "d2/d6c/structstd_1_1internal_1_1rb__tree__base" ],
        [ "rb_tree_key_wrapper", "d8/d30/structstd_1_1internal_1_1rb__tree__key__wrapper.html", "d8/d30/structstd_1_1internal_1_1rb__tree__key__wrapper" ],
        [ "rb_tree_traits", "d4/d92/structstd_1_1internal_1_1rb__tree__traits.html", "d4/d92/structstd_1_1internal_1_1rb__tree__traits" ],
        [ "slist_base_node", "d5/d40/structstd_1_1internal_1_1slist__base__node.html", "d5/d40/structstd_1_1internal_1_1slist__base__node" ],
        [ "type_with_alignment", "d1/de8/structstd_1_1internal_1_1type__with__alignment.html", "d1/de8/structstd_1_1internal_1_1type__with__alignment" ],
        [ "type_with_alignment< 0 >", "d3/df1/structstd_1_1internal_1_1type__with__alignment_3_010_01_4.html", null ],
        [ "type_with_alignment< 1 >", "d3/dc4/structstd_1_1internal_1_1type__with__alignment_3_011_01_4.html", "d3/dc4/structstd_1_1internal_1_1type__with__alignment_3_011_01_4" ],
        [ "type_with_alignment< 16 >", "d8/d16/structstd_1_1internal_1_1type__with__alignment_3_0116_01_4.html", "d8/d16/structstd_1_1internal_1_1type__with__alignment_3_0116_01_4" ],
        [ "type_with_alignment< 2 >", "dc/da9/structstd_1_1internal_1_1type__with__alignment_3_012_01_4.html", "dc/da9/structstd_1_1internal_1_1type__with__alignment_3_012_01_4" ],
        [ "type_with_alignment< 4 >", "d5/dea/structstd_1_1internal_1_1type__with__alignment_3_014_01_4.html", "d5/dea/structstd_1_1internal_1_1type__with__alignment_3_014_01_4" ],
        [ "type_with_alignment< 8 >", "d7/d28/structstd_1_1internal_1_1type__with__alignment_3_018_01_4.html", "d7/d28/structstd_1_1internal_1_1type__with__alignment_3_018_01_4" ]
      ] ],
      [ "math", null, [
        [ "boundingbox", "d0/d19/classstd_1_1math_1_1boundingbox.html", "d0/d19/classstd_1_1math_1_1boundingbox" ],
        [ "color", "d9/def/classstd_1_1math_1_1color.html", "d9/def/classstd_1_1math_1_1color" ],
        [ "colors_base", "de/de2/classstd_1_1math_1_1colors__base.html", "de/de2/classstd_1_1math_1_1colors__base" ],
        [ "matrix4x4", "d5/ded/classstd_1_1math_1_1matrix4x4.html", "d5/ded/classstd_1_1math_1_1matrix4x4" ],
        [ "physik", "d1/d7c/classstd_1_1math_1_1physik.html", "d1/d7c/classstd_1_1math_1_1physik" ],
        [ "physik_base", "d8/dae/classstd_1_1math_1_1physik__base.html", "d8/dae/classstd_1_1math_1_1physik__base" ],
        [ "plane", "dc/d81/classstd_1_1math_1_1plane.html", "dc/d81/classstd_1_1math_1_1plane" ],
        [ "quaternion", "db/d2d/classstd_1_1math_1_1quaternion.html", "db/d2d/classstd_1_1math_1_1quaternion" ],
        [ "ray", "dd/d62/classstd_1_1math_1_1ray.html", "dd/d62/classstd_1_1math_1_1ray" ],
        [ "rectangle", "de/d0f/classstd_1_1math_1_1rectangle.html", "de/d0f/classstd_1_1math_1_1rectangle" ],
        [ "vector2", "d6/dee/classstd_1_1math_1_1vector2.html", "d6/dee/classstd_1_1math_1_1vector2" ],
        [ "vector3", "d8/de6/classstd_1_1math_1_1vector3.html", "d8/de6/classstd_1_1math_1_1vector3" ],
        [ "vector4", "d4/d00/classstd_1_1math_1_1vector4.html", "d4/d00/classstd_1_1math_1_1vector4" ]
      ] ],
      [ "net", null, [
        [ "end_point", "d2/dba/classstd_1_1net_1_1end__point.html", "d2/dba/classstd_1_1net_1_1end__point" ],
        [ "ip_address4", "d0/d3d/classstd_1_1net_1_1ip__address4.html", "d0/d3d/classstd_1_1net_1_1ip__address4" ],
        [ "ip_address6", "d1/d4d/classstd_1_1net_1_1ip__address6.html", "d1/d4d/classstd_1_1net_1_1ip__address6" ],
        [ "ip_address_base", "dd/d9c/classstd_1_1net_1_1ip__address__base.html", "dd/d9c/classstd_1_1net_1_1ip__address__base" ]
      ] ],
      [ "__auto_ptr_base", "d7/d6a/classstd_1_1____auto__ptr__base.html", "d7/d6a/classstd_1_1____auto__ptr__base" ],
      [ "adler32", "d8/da6/classstd_1_1adler32.html", "d8/da6/classstd_1_1adler32" ],
      [ "aligned_as", "d9/d30/structstd_1_1aligned__as.html", "d9/d30/structstd_1_1aligned__as" ],
      [ "aligof", "dc/d08/structstd_1_1aligof.html", "dc/d08/structstd_1_1aligof" ],
      [ "allocator", "d7/d75/classstd_1_1allocator.html", "d7/d75/classstd_1_1allocator" ],
      [ "atomic", "da/dec/classstd_1_1atomic.html", "da/dec/classstd_1_1atomic" ],
      [ "atomic_spinlock", "d1/d68/classstd_1_1atomic__spinlock.html", "d1/d68/classstd_1_1atomic__spinlock" ],
      [ "auto_ptr", "d3/d99/classstd_1_1auto__ptr.html", "d3/d99/classstd_1_1auto__ptr" ],
      [ "auto_ptr_ref", "da/d7f/classstd_1_1auto__ptr__ref.html", "da/d7f/classstd_1_1auto__ptr__ref" ],
      [ "base_vector", "d3/d6d/structstd_1_1base__vector.html", "d3/d6d/structstd_1_1base__vector" ],
      [ "basic_string", "d4/de8/classstd_1_1basic__string.html", "d4/de8/classstd_1_1basic__string" ],
      [ "basic_stringstream", "dd/dbb/structstd_1_1basic__stringstream.html", "dd/dbb/structstd_1_1basic__stringstream" ],
      [ "bernstein", "d3/d55/classstd_1_1bernstein.html", "d3/d55/classstd_1_1bernstein" ],
      [ "bidirectional_iterator_tag", "da/d16/structstd_1_1bidirectional__iterator__tag.html", null ],
      [ "buffer_allocator", "db/d89/classstd_1_1buffer__allocator.html", "db/d89/classstd_1_1buffer__allocator" ],
      [ "clone_ptr", "d3/d9e/classstd_1_1clone__ptr.html", "d3/d9e/classstd_1_1clone__ptr" ],
      [ "clone_ptr_interface", "df/d21/classstd_1_1clone__ptr__interface.html", "df/d21/classstd_1_1clone__ptr__interface" ],
      [ "Console", "de/de6/classstd_1_1_console.html", null ],
      [ "cow_string_storage", "d8/de8/classstd_1_1cow__string__storage.html", "d8/de8/classstd_1_1cow__string__storage" ],
      [ "crc32", "df/dd6/classstd_1_1crc32.html", "df/dd6/classstd_1_1crc32" ],
      [ "default_delete", "d2/d44/structstd_1_1default__delete.html", "d2/d44/structstd_1_1default__delete" ],
      [ "delegate", "d2/d56/classstd_1_1delegate.html", "d2/d56/classstd_1_1delegate" ],
      [ "delegate_base", "db/ddb/classstd_1_1delegate__base.html", "db/ddb/classstd_1_1delegate__base" ],
      [ "delegateparam", "d4/ded/classstd_1_1delegateparam.html", "d4/ded/classstd_1_1delegateparam" ],
      [ "discard_block_engine", "d2/dee/classstd_1_1discard__block__engine.html", "d2/dee/classstd_1_1discard__block__engine" ],
      [ "equal_to", "d7/de9/structstd_1_1equal__to.html", "d7/de9/structstd_1_1equal__to" ],
      [ "event", "d5/d46/classstd_1_1event.html", "d5/d46/classstd_1_1event" ],
      [ "filestream", "de/dbc/classstd_1_1filestream.html", "de/dbc/classstd_1_1filestream" ],
      [ "fixed_array", "d0/d84/classstd_1_1fixed__array.html", "d0/d84/classstd_1_1fixed__array" ],
      [ "fixed_list", "d7/db1/classstd_1_1fixed__list.html", "d7/db1/classstd_1_1fixed__list" ],
      [ "fixed_sorted_vector", "d4/dfa/classstd_1_1fixed__sorted__vector.html", "d4/dfa/classstd_1_1fixed__sorted__vector" ],
      [ "fixed_substring", "db/d27/classstd_1_1fixed__substring.html", "db/d27/classstd_1_1fixed__substring" ],
      [ "fixed_vector", "d9/d50/classstd_1_1fixed__vector.html", "d9/d50/classstd_1_1fixed__vector" ],
      [ "fixed_vector_storage", "d0/d8e/structstd_1_1fixed__vector__storage.html", "d0/d8e/structstd_1_1fixed__vector__storage" ],
      [ "fletcher16", "d0/d37/classstd_1_1fletcher16.html", "d0/d37/classstd_1_1fletcher16" ],
      [ "fletcher32", "d9/d20/classstd_1_1fletcher32.html", "d9/d20/classstd_1_1fletcher32" ],
      [ "fnv1a", "d4/da3/classstd_1_1fnv1a.html", "d4/da3/classstd_1_1fnv1a" ],
      [ "forward_iterator_tag", "df/d4f/structstd_1_1forward__iterator__tag.html", null ],
      [ "greater", "dc/ddc/structstd_1_1greater.html", "dc/ddc/structstd_1_1greater" ],
      [ "has_cheap_compare", "dd/d84/structstd_1_1has__cheap__compare.html", null ],
      [ "has_trivial_assign", "d5/d78/structstd_1_1has__trivial__assign.html", "d5/d78/structstd_1_1has__trivial__assign" ],
      [ "has_trivial_constructor", "de/df7/structstd_1_1has__trivial__constructor.html", "de/df7/structstd_1_1has__trivial__constructor" ],
      [ "has_trivial_copy", "df/d37/structstd_1_1has__trivial__copy.html", "df/d37/structstd_1_1has__trivial__copy" ],
      [ "has_trivial_destructor", "d2/dc7/structstd_1_1has__trivial__destructor.html", "d2/dc7/structstd_1_1has__trivial__destructor" ],
      [ "hash", "d8/dcf/structstd_1_1hash.html", "d8/dcf/structstd_1_1hash" ],
      [ "hash< basic_string< E, TAllocator, TStorage > >", "d6/df1/structstd_1_1hash_3_01basic__string_3_01_e_00_01_t_allocator_00_01_t_storage_01_4_01_4.html", "d6/df1/structstd_1_1hash_3_01basic__string_3_01_e_00_01_t_allocator_00_01_t_storage_01_4_01_4" ],
      [ "hash_map", "d7/dfc/classstd_1_1hash__map.html", "d7/dfc/classstd_1_1hash__map" ],
      [ "hasher", "d3/d7e/classstd_1_1hasher.html", "d3/d7e/classstd_1_1hasher" ],
      [ "ifstream", "d6/de4/classstd_1_1ifstream.html", "d6/de4/classstd_1_1ifstream" ],
      [ "independent_bits_engine", "d5/d38/classstd_1_1independent__bits__engine.html", "d5/d38/classstd_1_1independent__bits__engine" ],
      [ "input_iterator_tag", "d2/d21/structstd_1_1input__iterator__tag.html", null ],
      [ "instream", "d8/d14/classstd_1_1instream.html", "d8/d14/classstd_1_1instream" ],
      [ "int_to_type", "dd/d80/structstd_1_1int__to__type.html", "dd/d80/structstd_1_1int__to__type" ],
      [ "intrusive_list", "d2/d23/classstd_1_1intrusive__list.html", "d2/d23/classstd_1_1intrusive__list" ],
      [ "intrusive_list_base", "db/d5f/classstd_1_1intrusive__list__base.html", "db/d5f/classstd_1_1intrusive__list__base" ],
      [ "intrusive_list_iterator", "d9/dcc/classstd_1_1intrusive__list__iterator.html", "d9/dcc/classstd_1_1intrusive__list__iterator" ],
      [ "intrusive_list_node", "dd/d52/structstd_1_1intrusive__list__node.html", "dd/d52/structstd_1_1intrusive__list__node" ],
      [ "intrusive_slist", "db/df2/classstd_1_1intrusive__slist.html", "db/df2/classstd_1_1intrusive__slist" ],
      [ "intrusive_slist_base", "dd/dbc/classstd_1_1intrusive__slist__base.html", "dd/dbc/classstd_1_1intrusive__slist__base" ],
      [ "intrusive_slist_iterator", "da/d4b/classstd_1_1intrusive__slist__iterator.html", "da/d4b/classstd_1_1intrusive__slist__iterator" ],
      [ "intrusive_slist_node", "d3/dc1/structstd_1_1intrusive__slist__node.html", "d3/dc1/structstd_1_1intrusive__slist__node" ],
      [ "iofstream", "d4/dae/classstd_1_1iofstream.html", "d4/dae/classstd_1_1iofstream" ],
      [ "iproperty_base", "de/d9b/classstd_1_1iproperty__base.html", "de/d9b/classstd_1_1iproperty__base" ],
      [ "is_floating_point", "dd/dca/structstd_1_1is__floating__point.html", "dd/dca/structstd_1_1is__floating__point" ],
      [ "is_floating_point< double >", "dc/d0a/structstd_1_1is__floating__point_3_01double_01_4.html", "dc/d0a/structstd_1_1is__floating__point_3_01double_01_4" ],
      [ "is_floating_point< float >", "db/d0d/structstd_1_1is__floating__point_3_01float_01_4.html", "db/d0d/structstd_1_1is__floating__point_3_01float_01_4" ],
      [ "is_fundamental", "df/d10/structstd_1_1is__fundamental.html", "df/d10/structstd_1_1is__fundamental" ],
      [ "is_integral", "de/d6a/structstd_1_1is__integral.html", "de/d6a/structstd_1_1is__integral" ],
      [ "is_pod", "da/da3/structstd_1_1is__pod.html", "da/da3/structstd_1_1is__pod" ],
      [ "is_pod< pair< T1, T2 > >", "d6/d1f/structstd_1_1is__pod_3_01pair_3_01_t1_00_01_t2_01_4_01_4.html", "d6/d1f/structstd_1_1is__pod_3_01pair_3_01_t1_00_01_t2_01_4_01_4" ],
      [ "is_pointer", "d0/dad/structstd_1_1is__pointer.html", "d0/dad/structstd_1_1is__pointer" ],
      [ "is_pointer< T * >", "d8/d97/structstd_1_1is__pointer_3_01_t_01_5_01_4.html", "d8/d97/structstd_1_1is__pointer_3_01_t_01_5_01_4" ],
      [ "isaac_engine", "db/d07/classstd_1_1isaac__engine.html", "db/d07/classstd_1_1isaac__engine" ],
      [ "iterator_traits", "db/dcf/structstd_1_1iterator__traits.html", "db/dcf/structstd_1_1iterator__traits" ],
      [ "iterator_traits< T * >", "d9/da2/structstd_1_1iterator__traits_3_01_t_01_5_01_4.html", "d9/da2/structstd_1_1iterator__traits_3_01_t_01_5_01_4" ],
      [ "less", "db/d0f/structstd_1_1less.html", "db/d0f/structstd_1_1less" ],
      [ "linear_congruential_engine", "db/d61/classstd_1_1linear__congruential__engine.html", "db/d61/classstd_1_1linear__congruential__engine" ],
      [ "list", "d4/dff/classstd_1_1list.html", "d4/dff/classstd_1_1list" ],
      [ "lock_base", "d5/da8/classstd_1_1lock__base.html", "d5/da8/classstd_1_1lock__base" ],
      [ "lock_util", "df/db8/classstd_1_1lock__util.html", "df/db8/classstd_1_1lock__util" ],
      [ "map", "d4/de8/classstd_1_1map.html", "d4/de8/classstd_1_1map" ],
      [ "memorystream", "d8/dd6/classstd_1_1memorystream.html", "d8/dd6/classstd_1_1memorystream" ],
      [ "mersenne_twister_engine", "dc/da4/classstd_1_1mersenne__twister__engine.html", "dc/da4/classstd_1_1mersenne__twister__engine" ],
      [ "mutex", "df/dc3/classstd_1_1mutex.html", "df/dc3/classstd_1_1mutex" ],
      [ "node_ptr", "d4/d30/classstd_1_1node__ptr.html", "d4/d30/classstd_1_1node__ptr" ],
      [ "object", "d8/d91/classstd_1_1object.html", null ],
      [ "ofstream", "d0/db3/classstd_1_1ofstream.html", "d0/db3/classstd_1_1ofstream" ],
      [ "output_iterator_tag", "d1/dbb/structstd_1_1output__iterator__tag.html", null ],
      [ "outstream", "dd/db5/classstd_1_1outstream.html", "dd/db5/classstd_1_1outstream" ],
      [ "pair", "d8/d71/structstd_1_1pair.html", "d8/d71/structstd_1_1pair" ],
      [ "radix_sorter", "d9/dd0/classstd_1_1radix__sorter.html", "d9/dd0/classstd_1_1radix__sorter" ],
      [ "ramakrishna", "d5/d05/classstd_1_1ramakrishna.html", "d5/d05/classstd_1_1ramakrishna" ],
      [ "random_access_iterator_tag", "d5/db6/structstd_1_1random__access__iterator__tag.html", null ],
      [ "rb_tree", "d8/d23/classstd_1_1rb__tree.html", "d8/d23/classstd_1_1rb__tree" ],
      [ "rb_tree_base", "da/d5a/classstd_1_1rb__tree__base.html", "da/d5a/classstd_1_1rb__tree__base" ],
      [ "ring_buffer", "d8/da5/classstd_1_1ring__buffer.html", "d8/da5/classstd_1_1ring__buffer" ],
      [ "ring_buffer_iterator", "db/dde/classstd_1_1ring__buffer__iterator.html", "db/dde/classstd_1_1ring__buffer__iterator" ],
      [ "save_ptr", "d4/d23/classstd_1_1save__ptr.html", "d4/d23/classstd_1_1save__ptr" ],
      [ "scoped_ptr", "d2/dcc/classstd_1_1scoped__ptr.html", "d2/dcc/classstd_1_1scoped__ptr" ],
      [ "shared_ptr", "df/ddb/classstd_1_1shared__ptr.html", "df/ddb/classstd_1_1shared__ptr" ],
      [ "shuffle_order_engine", "d5/df9/classstd_1_1shuffle__order__engine.html", "d5/df9/classstd_1_1shuffle__order__engine" ],
      [ "simple_string_storage", "d6/d62/classstd_1_1simple__string__storage.html", "d6/d62/classstd_1_1simple__string__storage" ],
      [ "simple_wstring_storage", "dc/d45/classstd_1_1simple__wstring__storage.html", "dc/d45/classstd_1_1simple__wstring__storage" ],
      [ "singleton", "d9/da8/classstd_1_1singleton.html", "d9/da8/classstd_1_1singleton" ],
      [ "slist", "d5/d64/classstd_1_1slist.html", "d5/d64/classstd_1_1slist" ],
      [ "sorted_vector", "d8/d6b/classstd_1_1sorted__vector.html", "d8/d6b/classstd_1_1sorted__vector" ],
      [ "spinlock", "d5/d7a/classstd_1_1spinlock.html", "d5/d7a/classstd_1_1spinlock" ],
      [ "stack", "db/d43/classstd_1_1stack.html", "db/d43/classstd_1_1stack" ],
      [ "stack_allocator", "d8/d28/classstd_1_1stack__allocator.html", "d8/d28/classstd_1_1stack__allocator" ],
      [ "standard_vector_storage", "db/dc3/structstd_1_1standard__vector__storage.html", "db/dc3/structstd_1_1standard__vector__storage" ],
      [ "stream", "df/d5b/classstd_1_1stream.html", "df/d5b/classstd_1_1stream" ],
      [ "string_rep", "d5/d88/structstd_1_1string__rep.html", "d5/d88/structstd_1_1string__rep" ],
      [ "subtract_with_carry_engine", "d7/d48/classstd_1_1subtract__with__carry__engine.html", "d7/d48/classstd_1_1subtract__with__carry__engine" ],
      [ "Sys", "da/d13/classstd_1_1_sys.html", "da/d13/classstd_1_1_sys" ],
      [ "thread", "d6/d35/classstd_1_1thread.html", "d6/d35/classstd_1_1thread" ],
      [ "value_property", "dd/dbc/classstd_1_1value__property.html", "dd/dbc/classstd_1_1value__property" ],
      [ "vector", "dd/d4e/classstd_1_1vector.html", "dd/d4e/classstd_1_1vector" ],
      [ "weak_ptr", "da/d49/classstd_1_1weak__ptr.html", "da/d49/classstd_1_1weak__ptr" ],
      [ "weinberg", "d3/d19/classstd_1_1weinberg.html", "d3/d19/classstd_1_1weinberg" ]
    ] ],
    [ "Client", "d3/d7a/class_client.html", "d3/d7a/class_client" ],
    [ "Server", "dc/db6/class_server.html", "dc/db6/class_server" ],
    [ "test", "de/d01/classtest.html", "de/d01/classtest" ]
];